EASYBLOGGER(1)
==============
:doctype: manpage


NAME
----
*easyblogger* - content management system


DESCRIPTION
-----------
*easyblogger* allows you to manage your blog-post easily. Following the UNIX-philosophy, it's completly configurable through text-files and command-line arguments.


BUGS
----
Please report bugs at <https://github.com/Florianjw/easyblogger>


AUTHOR
------
'Florian Weber' is the original author.


COPYING
-------
This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.