# for making the man-page out of the asciidoc-file:
man:
	a2x -f manpage documentation.asciidoc

# cleaning the directory:
clean:
	find -not -name "." -and -not -name "makefile" -and -not -name "documentation.asciidoc" -exec rm {} \;