
all:
	a2x -f manpage documentation.asciidoc
	a2x -f xhtml documentation.asciidoc

# for making the man-page out of the asciidoc-file:
man:
	a2x -f manpage documentation.asciidoc

# following generates a HTML-file (readable with a browser) out of the asciidoc-file:
html:
	a2x -f xhtml documentation.asciidoc

